version: b{build}
pull_requests:
  do_not_increment_build_number: true

clone_depth: 1
image: Visual Studio 2017
configuration: Debug

environment:
    WEEBHOOK_URL:
        secure: 5iyntOmaNX1ztZQHITwehOjGHrTQW9SzqnqigVtYWGs5hbJk6nhzxfw8G+TZiTboZ4Ma04xW7pDcjBjMHEui2FMjuf8raJPFTzR/sE6Xd+Q4CicdfBOdl2cbRmF8XFYtagf4n/K7U1QPVw/0QNetAGbuxZd2r8y4j44IV3FQuHE=

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - cmd: git submodule update --init --recursive
  - cmd: choco install resharper-clt -y
  - cmd: choco install nvika -y
  
before_build:
  - cmd: nuget restore -verbosity quiet

build:
  parallel: true
  verbosity: minimal

after_build:
  - cmd: inspectcode --o="inspectcodereport.xml" --projects:* --caches-home="inspectcode" Sora.sln > NUL
  - cmd: NVika parsereport "inspectcodereport.xml"
  
 on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEWBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEWBHOOK_URL